name: Build and publish to TestPyPI 🐍

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Configure Poetry
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_API_TOKEN  }}
      - name: Install dependencies
        run: poetry install
      - name: Build package
        run: poetry build
      - name: Publish package to TestPyPI
        run: poetry publish --skip-existing --repository test-pypi
